[project]
name = "mjolnir"
version = "0.1.0-dev"
authors = [{name = "Tom Scheeper",email = "tomscheeper@gmail.com"}]

dependencies = [
    "dotenv>=0.9.9",
    "keyboard>=0.13.5",
    "psutil>=7.1.3",
    "streamlit>=1.44.1",
]
